admin: fix release schedule EOL dates (#936)
* all future release and EOL dates on Wednesdays
* v7 with EOL 2025

Reviewed-on: https://codeberg.org/forgejo/docs/pulls/936
Reviewed-by: Earl Warren <earl-warren@noreply.codeberg.org>
Co-authored-by: Robert Wolff <mahlzahn@posteo.de>
Co-committed-by: Robert Wolff <mahlzahn@posteo.de>

diff --git a/.forgejo/workflows/pr.yml b/.forgejo/workflows/pr.yml
--- a/.forgejo/workflows/pr.yml
+++ b/.forgejo/workflows/pr.yml
@@ -26,7 +26,7 @@ jobs:
       - name: release-schedule
         run: |
           pnpm run update-schedule
-          git diff --exit-code
+          git diff --exit-code || (echo "Error: Run 'pnpm run update-schedule' to generate the markdown release schedule and commit it" && false)
       - name: get forgejo.org and move the docs
         run: |
           git clone --recursive --depth 1 https://codeberg.org/forgejo/website/ /tmp/website
